### ISSUE TITLE
Missing type for array<string, mixed>

### ISSUE THREAD

**Issue by wizhippo** [phpDocumentor/TypeResolver#89] opened 2019-12-27 13:48 UTC
I am getting

'A type is missing in a collection expression'

Which is cause by the doc block `@var array<string, mixed>` such as found at https://github.com/netgen-layouts/layouts-core/blob/7fbe0c1b0619fc8f33dacddeea2ada7af484a4b8/lib/API/Values/Block/BlockUpdateStruct.php#L76.

`array<string, mixed>` is generated suing phpStan.  I believe array<string, mixed> is a valid type.

**Comment by jaapio** [comment] 2019-12-27 13:56
Thanks for reaching out.
Our typeresolver does support the generics notation that is also supported by phpstan. But our docblockReflection component does not have support for it yet. That component would need a major redesign to be able to support this. But it does not have our focus yet because we think there are more important things to do right now.

Because of the impact on the library is this big and it is used very often in the php ecosystem we want to be really careful with large changes like the redesign which is needed to support generics.

**Comment by wizhippo** [comment] 2019-12-27 14:13
@jaapio Thank you for clarifying.   @emoderic not sure if phpstan has an option to emit differently or how to solve this one until docblockReflection supports it.  I believe the issue comes up during form validation as shown in this trace https://gist.github.com/wizhippo/6ac7dd53f1a2aeccfec92b230cb4089b.

@jaapio I'll leave you to close this issue when you believe it is appropriate.

**Comment by jaapio** [comment] 2019-12-27 14:20
Ah that issue, it is caused by a breaking change in our docblockReflection component. A fix is already https://github.com/phpDocumentor/ReflectionDocBlock/pull/191 this will be merged and released soon.

**Closed** 2019-12-27 14:20 UTC

**Comment by emodric** [comment] 2019-12-27 14:26
Thanks for the details @jaapio ! :+1:

**Comment by jaapio** [comment] 2019-12-28 21:30
FYI: https://github.com/symfony/symfony/pull/35134

Run `composer update` to get the latest version of our docblockReflection library, that will fix your issue.
