### ISSUE TITLE
Pseudo-types and variables from php.net

### ISSUE THREAD

**Issue by spencerbaynton** [phpDocumentor/TypeResolver#15] opened 2016-01-24 02:32 UTC
php.net has a page [Pseudo-types and variables used in this documentation](https://secure.php.net/manual/en/language.pseudo-types.php). It includes some of the types phpDocumentor already includes (i.e. `mixed`, `callback`, `void`), but also includes others like _number_ (indicates that a parameter can be either integer or float). For example `number` is used in the definition of [array_sum](https://secure.php.net/manual/en/function.array-sum.php). Should phpDocumentor also support these other pseudo-types and variables?

**Comment by mvriel** [comment] 2016-01-28 13:08
As far as I can see the only one not supported is the `number` and `$...` mentions. The problem is that any added type may not be used as a class name anymore and since `number` is not an official keyword (and classes exist with that name) and its relatively low added value I prefer not to add it at this stage.

Should number become a keyword in the future we can reconsider this as we can then safely use it without ambiguity for resolving type vs classnames.

The `$...` mention is more of an operator/modifier than a type and with phpDocumentor we have chosen to not handle this in the TypeResolver but to handle that in the project itself (since it signifies a repetition of variables and not a type for a single modifier)

**Comment by GrahamCampbell** [comment] 2017-12-29 23:36
I think this can be safely closed?

**Closed** 2018-08-09 15:14 UTC
